DROP TABLE chinaaqi;

CREATE DATABASE aqicn;
DROP TABLE aqicn.TBL_AQI_CN;
CREATE TABLE aqicn.TBL_AQI_CN(
   CITY_NAME  VARCHAR(128) NOT NULL,
   PRCSS_TIME  DATETIME NOT NULL,
   AQI_VALUE SMALLINT,
   X_VALUE   SMALLINT,
   POL_TYPE  VARCHAR(128),
   Longitude DECIMAL(20,15), #经度
   Latitude  DECIMAL(20,15), #维度
   CREATE_TS    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   UPDATE_TS    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY(CITY_NAME, PRCSS_TIME)
);

CREATE VIEW aqicn.VW_CUR_AQI_CN AS
SELECT 
	CITY_NAME,
	PRCSS_TIME,
	AQI_VALUE,
	X_VALUE,
	POL_TYPE,
	Longitude,
	Latitude
FROM aqicn.TBL_AQI_CN
WHERE (CITY_NAME , PRCSS_TIME) IN (
	SELECT CITY_NAME, MAX(PRCSS_TIME) PRCSS_TIME
	FROM aqicn.TBL_AQI_CN
	GROUP BY CITY_NAME
);


SELECT T1.* FROM
  aqicn.TBL_AQI_CN T1,
  (SELECT
      max(longitude) longitude,
      max(latitude) latitude,
      max(PRCSS_TIME) PRCSS_TIME,
      city_name
   FROM aqicn.TBL_AQI_CN
      WHERE city_name = 'Shanghai (上海)'
   GROUP BY city_name) T2
WHERE
   POWER(T1.longitude-T2.longitude,2) + POWER(T1.latitude-T2.latitude,2) <=0.3 AND
   T1.PRCSS_TIME = T2.PRCSS_TIME
ORDER BY POWER(T1.longitude-T2.longitude,2) + POWER(T1.latitude-T2.latitude,2);





SELECT COUNT(1) FROM aqicn.TBL_AQI_CN
      WHERE city_name = 'Shanghai (上海)'

SELECT * FROM aqicn.TBL_AQI_CN
WHERE lower(city_name) like '%shanghai%';

SELECT * FROM aqicn.TBL_AQI_CN
WHERE city_name ='Beijing (北京)' ;


INSERT INTO aqicn.TBL_AQI_CN(CITY_NAME, PRCSS_TIME, AQI_VALUE, X_VALUE, Longitude, Latitude, POL_TYPE, UPDATE_TS)VALUES('Laiwu (莱芜)', STR_TO_DATE('201409184:00','%Y%m%d%H:%i'), 384, 1516, 117.676731, 36.213691, 'pm2.5', CURRENT_TIMESTAMP) ON DUPLICATE KEY UPDATE AQI_VALUE = 384, UPDATE_TS = CURRENT_TIMESTAMP;
