DROP TABLE chinaaqi;

CREATE DATABASE aqicn;
DROP TABLE aqicn.TBL_AQI_CN;
CREATE TABLE aqicn.TBL_AQI_CN(
   CITY_NAME  VARCHAR(128) NOT NULL,
   PRCSS_TIME  DATETIME NOT NULL,
   AQI_VALUE SMALLINT,
   X_VALUE   SMALLINT,
   Longitude DECIMAL(20,15), #经度
   Latitude  DECIMAL(20,15), #维度
   CREATE_TS    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   UPDATE_TS    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY(CITY_NAME, PRCSS_TIME)
);

select * from aqicn.TBL_AQI_CN
WHERE CITY_NAME LIKE '%上海%';

INSERT INTO aqicn.TBL_AQI_CN(
CITY_NAME, PRCSS_TIME, AQI_VALUE, X_VALUE, Longitude, Latitude, UPDATE_TS
)
VALUES('shanghai', STR_TO_DATE('201409180700','%Y%m%d%H%i'), 123, 1231, 121.121, 31.213, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE AQI_VALUE = 125, UPDATE_TS = CURRENT_TIMESTAMP;


INSERT INTO aqicn.TBL_AQI_CN(CITY_NAME, PRCSS_TIME, AQI_VALUE, X_VALUE, Longitude, Latitude, UPDATE_TS)VALUES('Laiwu (莱芜)', STR_TO_DATE('201409184:00','%Y%m%d%H:%i'), 384, 1516, 117.676731, 36.213691, CURRENT_TIMESTAMP) ON DUPLICATE KEY UPDATE AQI_VALUE = 384, UPDATE_TS = CURRENT_TIMESTAMP;

INSERT INTO V(CITY_NAME, PRCSS_TIME, AQI_VALUE, X_VALUE, Longitude, Latitude, UPDATE_TS)VALUES('Prabadang Rehabiltation Center, Samut Prakan (ศูนย์ฟื้นฟูอาชีพคนพิการและทุพลภาพ สมุทรปราการ)', STR_TO_DATE('2014091808:00','%Y%m%d%H:%i'), 0, 1836, 100.54340633012, 13.66402619452, CURRENT_TIMESTAMP) ON DUPLICATE KEY UPDATE AQI_VALUE = 0, UPDATE_TS = CURRENT_TIMESTAMP;