CREATE DATABASE kitco;

CREATE TABLE kitco.TBL_CURNCY_FCT(
   CURNCY_TYPE  VARCHAR(64) NOT NULL,
   CURNCY_TIME  DATETIME NOT NULL,
   CURNCY_VALUE DECIMAL(20,10),
   CREATE_TS    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   UPDATE_TS    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY(CURNCY_TYPE, CURNCY_TIME)
);

DELETE FROM kitco.TBL_CURNCY_FCT;
SELECT * FROM kitco.TBL_CURNCY_FCT where curncy_type ='BRL'
order by CURNCY_TIME desc;
select distinct CURNCY_TYPE from kitco.TBL_CURNCY_FCT;
select count(1), curncy_type from kitco.TBL_CURNCY_FCT
group by curncy_type


#INSERT INTO kitco.TBL_CURNCY_FCT(CURNCY_TYPE, CURNCY_TIME, CURNCY_VALUE) values('USD1', STR_TO_DATE('20140917070401','%Y%m%d%H%i%s'), 1.9018);
#INSERT INTO kitco.TBL_CURNCY_FCT(CURNCY_TYPE, CURNCY_TIME, CURNCY_VALUE) values('USD1', STR_TO_DATE('20140917070402','%Y%m%d%H%i%s'), 1.9018);

#INSERT INTO kitco.TBL_CURNCY_FCT(CURNCY_TYPE, CURNCY_TIME, CURNCY_VALUE, UPDATE_TS) VALUES('USD1', STR_TO_DATE('20140917070403','%Y%m%d%H%i%s'), 1.9011, CURRENT_TIMESTAMP) ON DUPLICATE KEY UPDATE CURNCY_VALUE = 1.9011, UPDATE_TS = CURRENT_TIMESTAMP;

# Error 1175
# Workbench [Edit]->[Preferences...]
# [SQL Query] [Forbid UPDATE and DELETE statements without a WHERE clause (safe updates)] 

